### ISSUE TITLE
Error while running this script on Exch 2013 CU12

### ISSUE THREAD

**Issue by senthams** [cunninghamp/Get-CASHealth.ps1#1]
Hi There, 

Our Servers CAS servers were on CU4 and recently we upgraded to CU12. Cashealth.ps1 was working fine in CU4 and now with CU12 its giving an error 

Cannot process argument transformation on parameter 'Server'. Cannot convert value "Server01" to type
"Microsoft.Exchange.Configuration.Tasks.ServerIdParameter". Error: "Cannot convert hashtable to an object of the
following type: Microsoft.Exchange.Configuration.Tasks.ServerIdParameter. Hashtable-to-Object conversion is not
supported in restricted language mode or a Data section."
    + CategoryInfo          : InvalidData: (:) [Get-ActiveSyncVirtualDirectory], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-ActiveSyncVirtualDirectory
    + PSComputerName        

any help would be greatly appreciated.

Thanks
Senthams

**Comment by cunninghamp** [comment]
Are you running the script in the Exchange Management Shell on the server?

**Comment by senthams** [comment]
Yes, running it on a local server with exchange management shell.

**Comment by cunninghamp** [comment]
Ok. I don't have a CU12 box, but it works fine on my CU13 server. So pls let me know if this error still occurs after you've updated to CU13 (or CU14 that was released this week).

**Comment by senthams** [comment]
Thanks, its an ENT and we just upgraded to CU12. I am not sure how long its going to take us to get to CU13 or CU14. Thanks anyways,

**Comment by cunninghamp** [comment]
As this CU is out of support and I have no way to test this scenario I am closing this issue.
