### ISSUE TITLE
Should add "-UseBasicParsing"

### ISSUE THREAD

**Issue by maxpaynejeju** [cunninghamp/Get-CASHealth.ps1#2]
I used the script and for most of the URLs it gave "error". 
When I tried to access the URLs on browser I was getting "200 OK<br/>URL" 

I tried to run the URLs using "Invoke-WebRequest -Uri " and got the following error:
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:1
+ Invoke-WebRequest -Uri https://mail.exchangeurl.com/owa/healthcheck.htm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Upon editing the script and adding "-UseBasicParsing" to "Invoke-WebRequest" command, now it's working fine.

**Comment by cunninghamp** [comment]
Tested on WS2019 with EX2019 and didn't have any issues, but adding -UseBasicParsing also didn't cause any problems, so I have updated the script.
